### ISSUE TITLE
Notice: Undefined variable: message in vendor\eden\core\src\Argument.php on line 54

### ISSUE THREAD

**Issue by netbasejsc** [Eden-PHP/Mysql#6]
Hello,

After I installed the latest version via composer and  run 
`$database = eden('mysql', '[HOST]' ,'[DBNAME]', '[USER]', '[PASS]'); //instantiate`
I get a msg:
Fatal error: Call to undefined function eden() in /index.php on line 
I search this error on google and see this issues https://github.com/Eden-PHP/Mysql/issues/1
I add Eden::DECORATOR; after require autoload

`require_once __DIR__.'/vendor/autoload.php';
Eden::DECORATOR;`
And I get a new php error:
```
Notice: Undefined variable: message in D:\HomeServer\htdocs\phpdemo\mail\vendor\eden\core\src\Argument.php on line 54

Notice: Undefined variable: code in D:\HomeServer\htdocs\phpdemo\mail\vendor\eden\core\src\Argument.php on line 54
```
Please help me, thanks!

**Comment by kevinp1005** [comment]
@netbasejsc Hi, so what was the solution for this ? I currently have the same exact error

**Comment by cblanquera** [comment]
----

## Enable Eden

The following documentation uses `eden()` in its example reference. Enabling this function requires an extra step as descirbed in this section which is not required if you access this package using the following.

```
Eden\Core\Control::i();
```

When using composer, there is not an easy way to access functions from packages. As a workaround, adding this constant in your code will allow `eden()` to be available after. 

```
Eden::DECORATOR;
```

For example:

```
Eden::DECORATOR;

eden()->inspect('Hello World');
```

----

**Comment by cblanquera** [comment]
This project has been through several iterations over the years and has ended up at https://github.com/CradlePHP/Storm - This is maintained regularly currently

**Comment by shahmir811** [comment]
I have the same issue, not resolved even after using Eden::DECORATOR; ...
